version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - "5433:5432"
    env_file:
      - .env
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app
    env_file:
      - .env
    command: [/app/docker/app/startup.sh]
    ports:
      - "8001:8000"
    depends_on:
      - db